import {useCallback,useEffect,useState} from "react";
import {apiFetch} from "../../services/api";
import {useAuth} from "../../hooks/useAuth";

const money=(n)=>Number(n||0).toLocaleString("es-EC",{style:"currency",currency:"USD"});
export default function Caja(){
 const{user}=useAuth(),[caja,setCaja]=useState(null),[historial,setHistorial]=useState([]),[monto,setMonto]=useState(""),[observaciones,setObservaciones]=useState(""),[filtros,setFiltros]=useState({desde:"",hasta:"",cajero:""}),[mensaje,setMensaje]=useState("");
 const cargar=useCallback(async()=>{try{const q=new URLSearchParams(Object.entries(filtros).filter(([,v])=>v));const[actual,rows]=await Promise.all([apiFetch("/caja"),apiFetch(`/caja/historial?${q}`)]);setCaja(actual);setHistorial(rows)}catch(e){setMensaje(e.message)}},[filtros]);useEffect(()=>{cargar()},[cargar]);
 const operar=async(tipo)=>{try{const data=await apiFetch(`/caja/${tipo}`,{method:"POST",body:{[tipo==="abrir"?"monto_apertura":"monto_cierre"]:monto,observaciones}});setMensaje(tipo==="cerrar"?`Caja cerrada. Diferencia: ${money(data.diferencia)}`:"Caja abierta");setMonto("");setObservaciones("");cargar()}catch(e){setMensaje(e.message)}};
 const imprimir=()=>window.print();
 return <section className="module-page"><header className="page-header"><div><h1>Caja</h1><p>{caja?"Turno abierto":"Sin turno abierto"}</p></div><button className="secondary" onClick={imprimir}>Imprimir historial</button></header>{mensaje&&<div className="notice">{mensaje}</div>}
 <div className="summary-grid"><article><span>Monto de apertura</span><strong>{money(caja?.monto_apertura)}</strong></article><article><span>Estado</span><strong>{caja?.estado??"Cerrada"}</strong></article></div>
 <div className="form-grid"><label>{caja?"Efectivo declarado":"Monto de apertura"}<input type="number" min="0" step="0.01" value={monto} onChange={e=>setMonto(e.target.value)}/></label>{caja&&<label>Observaciones<textarea value={observaciones} onChange={e=>setObservaciones(e.target.value)} placeholder="Motivo de sobrante/faltante, si aplica"/></label>}<div className="form-actions"><button disabled={monto===""} onClick={()=>operar(caja?"cerrar":"abrir")}>{caja?"Cerrar y arquear":"Abrir caja"}</button></div></div>
 <h2>Historial de cierres</h2><div className="filters"><label>Desde<input type="date" value={filtros.desde} onChange={e=>setFiltros({...filtros,desde:e.target.value})}/></label><label>Hasta<input type="date" value={filtros.hasta} onChange={e=>setFiltros({...filtros,hasta:e.target.value})}/></label>{user?.rol==="Administrador"&&<label>ID cajero<input type="number" value={filtros.cajero} onChange={e=>setFiltros({...filtros,cajero:e.target.value})}/></label>}</div>
 <div className="table-wrap"><table><thead><tr><th>Apertura</th><th>Cierre</th><th>Cajero</th><th>Inicial</th><th>Ventas efectivo</th><th>Declarado</th><th>Diferencia</th><th>Estado</th><th>Observaciones</th></tr></thead><tbody>{historial.map(x=><tr key={x.id_caja_turno}><td>{new Date(x.abierto_en).toLocaleString()}</td><td>{x.cerrado_en?new Date(x.cerrado_en).toLocaleString():"—"}</td><td>{x.cajero}</td><td>{money(x.monto_apertura)}</td><td>{money(x.ventas_efectivo)}</td><td>{x.monto_cierre==null?"—":money(x.monto_cierre)}</td><td className={Number(x.diferencia)!==0?"amount-alert":""}>{x.diferencia==null?"—":money(x.diferencia)}</td><td>{x.estado==="Cerrada"?(Number(x.diferencia)===0?"Cerrado correctamente":"Con diferencia"):"Abierta"}</td><td>{x.observaciones||"—"}</td></tr>)}</tbody></table></div></section>;
}
