import { useCallback, useEffect, useState } from "react";
import { FlaskConical, Printer, Send } from "lucide-react";
import { apiFetch } from "../../services/api";
import { useAuth } from "../../hooks/useAuth";
import { CrudPage } from "../../components/CrudPage";

const fields=[{name:"id_historia",label:"ID historia",type:"number",required:true},{name:"id_paciente",label:"ID paciente",type:"number",required:true},{name:"od_esfera",label:"OD esfera",type:"number",step:"0.01"},{name:"od_cilindro",label:"OD cilindro",type:"number",step:"0.01"},{name:"od_eje",label:"OD eje",type:"number"},{name:"oi_esfera",label:"OI esfera",type:"number",step:"0.01"},{name:"oi_cilindro",label:"OI cilindro",type:"number",step:"0.01"},{name:"oi_eje",label:"OI eje",type:"number"},{name:"adicion",label:"Adición",type:"number",step:"0.01"},{name:"dnp",label:"DNP"},{name:"av_vl",label:"AV VL"},{name:"av_vp",label:"AV VP"},{name:"tipo_lente",label:"Tipo de lente"},{name:"material",label:"Material"},{name:"filtro",label:"Filtro"},{name:"prisma",label:"Prisma"},{name:"observaciones",label:"Observaciones",type:"textarea"}];

export default function Recetas(){
 const {user}=useAuth();const[recipes,setRecipes]=useState([]),[orders,setOrders]=useState([]),[labs,setLabs]=useState([]),[order,setOrder]=useState({id_receta:"",id_laboratorio:"",descripcion:""}),[lab,setLab]=useState({nombre:"",telefono:"",correo:"",direccion:""}),[message,setMessage]=useState(""),[printData,setPrintData]=useState(null);
 const load=useCallback(async()=>{try{const[r,o,l]=await Promise.all([apiFetch("/recetas"),apiFetch("/recetas/pedidos"),apiFetch("/recetas/laboratorios")]);setRecipes(r);setOrders(o);setLabs(l)}catch(error){setMessage(error.message)}},[]);useEffect(()=>{load()},[load]);
 const createOrder=async(event)=>{event.preventDefault();try{await apiFetch("/recetas/pedidos",{method:"POST",body:order});setOrder({id_receta:"",id_laboratorio:"",descripcion:""});setMessage("Pedido enviado al laboratorio");load()}catch(error){setMessage(error.message)}};
 const update=async(id,data)=>{try{const result=await apiFetch("/recetas/pedidos/"+id,{method:"PUT",body:data});setMessage("Pedido actualizado");load();return result}catch(error){setMessage(error.message)}};
 const createLab=async(event)=>{event.preventDefault();try{await apiFetch("/recetas/laboratorios",{method:"POST",body:lab});setLab({nombre:"",telefono:"",correo:"",direccion:""});setMessage("Laboratorio creado");load()}catch(error){setMessage(error.message)}};
 const printRecipe=async(row)=>{try{const data=await apiFetch("/recetas/"+row.id_receta+"/imprimir",{method:"POST"});setPrintData({type:"recipe",...data});setTimeout(()=>window.print(),200)}catch(error){setMessage(error.message)}};
 const printOrder=async(row)=>{await update(row.id_pedido_laboratorio,{impreso:true});setPrintData({type:"order",...row});setTimeout(()=>window.print(),200)};
 const printAction=Object.assign(printRecipe,{label:"Imprimir"});
 return <section className="module-page prescription-page"><div className="screen-content">{message&&<div className="notice">{message}</div>}<CrudPage title="Recetas ópticas" endpoint="/recetas" createLabel="Nueva receta" columns={[{key:"id_receta",label:"ID"},{key:"paciente_nombre",label:"Paciente"},{key:"od_esfera",label:"OD esfera"},{key:"od_cilindro",label:"OD cilindro"},{key:"oi_esfera",label:"OI esfera"},{key:"oi_cilindro",label:"OI cilindro"},{key:"creado_en",label:"Fecha"}]} fields={fields} rowAction={printAction}/>
 <h2><Send size={17}/> Nuevo pedido de laboratorio</h2><form className="form-grid" onSubmit={createOrder}><label>Receta<select required value={order.id_receta} onChange={(e)=>setOrder({...order,id_receta:e.target.value})}><option value="">Seleccione</option>{recipes.map((r)=><option key={r.id_receta} value={r.id_receta}>#{r.id_receta} · {r.paciente_nombre} {r.paciente_apellido}</option>)}</select></label><label>Laboratorio<select value={order.id_laboratorio} onChange={(e)=>setOrder({...order,id_laboratorio:e.target.value})}><option value="">Seleccione</option>{labs.map((l)=><option key={l.id_laboratorio} value={l.id_laboratorio}>{l.nombre}</option>)}</select></label><label>Descripción<textarea value={order.descripcion} onChange={(e)=>setOrder({...order,descripcion:e.target.value})}/></label><div className="form-actions"><button>Crear pedido</button></div></form>
 {user?.rol==="Administrador"&&<><h2><FlaskConical size={17}/> Laboratorios</h2><form className="form-grid" onSubmit={createLab}>{Object.keys(lab).map((key)=><label key={key}>{key.replaceAll("_"," ")}<input required={key==="nombre"} value={lab[key]} onChange={(e)=>setLab({...lab,[key]:e.target.value})}/></label>)}<div className="form-actions"><button>Guardar laboratorio</button></div></form></>}
 <h2>Seguimiento y ensamblaje</h2><div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Paciente</th><th>Laboratorio</th><th>Estado</th><th>Ensamblaje</th><th>Acciones</th></tr></thead><tbody>{orders.map((item)=><tr key={item.id_pedido_laboratorio}><td>LAB-{String(item.id_pedido_laboratorio).padStart(5,"0")}</td><td>{item.paciente_apellido} {item.paciente_nombre}</td><td>{item.laboratorio_nombre||"Por asignar"}</td><td><select value={item.estado} onChange={(e)=>update(item.id_pedido_laboratorio,{estado:e.target.value})}>{["Enviado","Recibido","En proceso","Listo","Entregado","Cancelado"].map((state)=><option key={state}>{state}</option>)}</select></td><td><select value={item.estado_ensamblaje} onChange={(e)=>update(item.id_pedido_laboratorio,{estado_ensamblaje:e.target.value})}>{["Pendiente","En proceso","Ensamblado","Entregado"].map((state)=><option key={state}>{state}</option>)}</select></td><td><button onClick={()=>printOrder(item)}><Printer size={14}/> Imprimir</button></td></tr>)}</tbody></table></div></div>
 {printData&&<article className="print-document"><header><div><h1>Óptica Integral</h1><p>{printData.type==="recipe"?"Receta optométrica":"Orden de laboratorio"}</p></div><strong>{printData.type==="recipe"?"REC-"+String(printData.id_receta).padStart(6,"0"):"LAB-"+String(printData.id_pedido_laboratorio).padStart(5,"0")}</strong></header><section><p><b>Paciente:</b> {printData.paciente_nombre} {printData.paciente_apellido}</p><p><b>Fecha:</b> {new Date(printData.creado_en||printData.fecha_envio).toLocaleString()}</p>{printData.type==="recipe"?<><table><thead><tr><th>Ojo</th><th>Esfera</th><th>Cilindro</th><th>Eje</th></tr></thead><tbody><tr><td>OD</td><td>{printData.od_esfera||"—"}</td><td>{printData.od_cilindro||"—"}</td><td>{printData.od_eje||"—"}</td></tr><tr><td>OI</td><td>{printData.oi_esfera||"—"}</td><td>{printData.oi_cilindro||"—"}</td><td>{printData.oi_eje||"—"}</td></tr></tbody></table><p><b>Adición:</b> {printData.adicion||"—"} · <b>DNP:</b> {printData.detalles?.dnp||"—"}</p><p><b>Observaciones:</b> {printData.observaciones||"—"}</p><div className="signature-line">Firma del optómetra<br/>{printData.optometra_nombre} {printData.optometra_apellido}</div></>:<><p><b>Laboratorio:</b> {printData.laboratorio_nombre||"Por asignar"}</p><p><b>Descripción:</b> {printData.descripcion||"—"}</p><p><b>Estado:</b> {printData.estado} · <b>Ensamblaje:</b> {printData.estado_ensamblaje}</p></>}</section></article>}
 </section>;
}
