import { useCallback, useEffect, useState } from "react";
import { Activity, Plus } from "lucide-react";
import { apiFetch } from "../../services/api";

const empty={id_paciente:"",id_cita:"",ojo_derecho:"",ojo_izquierdo:"",diagnostico:"",observacion:""};
export default function Examenes(){
 const[rows,setRows]=useState([]),[patients,setPatients]=useState([]),[appointments,setAppointments]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[open,setOpen]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{const[e,p,c]=await Promise.all([apiFetch("/examenes"),apiFetch("/pacientes"),apiFetch("/citas")]);setRows(e);setPatients(p);setAppointments(c.filter((item)=>item.pago_previo&&!["Cancelada","No asistio"].includes(item.estado)))}catch(error){setMessage(error.message)}},[]);useEffect(()=>{load()},[load]);
 const save=async(event)=>{event.preventDefault();try{await apiFetch(edit?"/examenes/"+edit:"/examenes",{method:edit?"PUT":"POST",body:form});setForm(empty);setEdit(null);setOpen(false);setMessage("Examen guardado");load()}catch(error){setMessage(error.message)}};
 const startEdit=(row)=>{setForm({id_paciente:row.id_paciente||"",id_cita:row.id_cita||"",ojo_derecho:row.ojo_derecho||"",ojo_izquierdo:row.ojo_izquierdo||"",diagnostico:row.diagnostico||"",observacion:row.observacion||""});setEdit(row.id_examen);setOpen(true)};
 return <section className="module-page"><header className="page-header"><div><span className="eyebrow">Evaluación clínica</span><h1>Exámenes visuales</h1><p>Solo se muestran citas con pago confirmado.</p></div><button onClick={()=>{setOpen(!open);setForm(empty);setEdit(null)}}><Plus size={17}/> {open?"Cancelar":"Nuevo examen"}</button></header>{message&&<div className="notice">{message}</div>}{open&&<form className="clinical-section" onSubmit={save}><h2><Activity size={19}/>{edit?"Actualizar examen":"Registro visual"}</h2><div className="field-grid cols-3"><label>Paciente<select required disabled={Boolean(edit)} value={form.id_paciente} onChange={(e)=>setForm({...form,id_paciente:e.target.value,id_cita:""})}><option value="">Seleccione</option>{patients.map((p)=><option key={p.id_paciente} value={p.id_paciente}>{p.apellido} {p.nombre}</option>)}</select></label><label>Cita pagada<select required disabled={Boolean(edit)} value={form.id_cita} onChange={(e)=>setForm({...form,id_cita:e.target.value})}><option value="">Seleccione</option>{appointments.filter((c)=>!form.id_paciente||String(c.id_paciente)===String(form.id_paciente)).map((c)=><option key={c.id_cita} value={c.id_cita}>#{c.id_cita} · {String(c.fecha_cita).slice(0,10)}</option>)}</select></label>{["ojo_derecho","ojo_izquierdo","diagnostico"].map((key)=><label key={key}>{key.replaceAll("_"," ")}<input value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="wide">Observación<textarea value={form.observacion} onChange={(e)=>setForm({...form,observacion:e.target.value})}/></label></div><div className="form-actions" style={{marginTop:16}}><button>Guardar examen</button></div></form>}<div className="table-wrap"><table><thead><tr><th>Paciente</th><th>OD</th><th>OI</th><th>Diagnóstico</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id_examen}><td>{row.paciente_apellido} {row.paciente_nombre}</td><td>{row.ojo_derecho||"—"}</td><td>{row.ojo_izquierdo||"—"}</td><td>{row.diagnostico||"—"}</td><td>{new Date(row.fecha_examen).toLocaleString()}</td><td><button onClick={()=>startEdit(row)}>Editar</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No hay exámenes registrados.</div>}</div></section>;
}
