import {useCallback,useEffect,useMemo,useState} from "react";
import {apiFetch} from "../../services/api";
import {useAuth} from "../../hooks/useAuth";

const linea=()=>({id_producto:"",descripcion:"",cantidad:1,precio_unitario:""});
const pago=()=>({forma_pago:"Efectivo",monto:"",referencia:""});
export default function Facturacion(){
 const{user}=useAuth();const[facturas,setFacturas]=useState([]),[productos,setProductos]=useState([]),[pacientes,setPacientes]=useState([]),[promos,setPromos]=useState([]);
 const[form,setForm]=useState({id_paciente:"",id_receta:"",id_historia:"",id_promocion:"",descuento:0,impuestos:0,dias_credito:30}),[detalles,setDetalles]=useState([linea()]),[pagos,setPagos]=useState([pago()]);
 const[accion,setAccion]=useState(null),[accionForm,setAccionForm]=useState({motivo:"",monto:"",reponer_stock:true}),[promo,setPromo]=useState({nombre:"",porcentaje:""}),[msg,setMsg]=useState(""),[printData,setPrintData]=useState(null);
 const load=useCallback(async()=>{try{const[f,p,pa,pr]=await Promise.all([apiFetch("/facturacion"),apiFetch("/inventario"),apiFetch("/pacientes"),apiFetch("/facturacion/promociones")]);setFacturas(f);setProductos(p);setPacientes(pa);setPromos(pr)}catch(e){setMsg(e.message)}},[]);useEffect(()=>{load()},[load]);
 const subtotal=useMemo(()=>detalles.reduce((s,d)=>s+Number(d.cantidad||0)*Number(d.precio_unitario||0),0),[detalles]);const selectedPromo=promos.find(p=>String(p.id_promocion)===String(form.id_promocion));const total=subtotal-Number(form.descuento||0)-(selectedPromo?subtotal*Number(selectedPromo.porcentaje)/100:0)+Number(form.impuestos||0);const pagado=pagos.reduce((s,p)=>s+Number(p.monto||0),0);
 const updateDetalle=(i,key,value)=>setDetalles(detalles.map((d,n)=>n===i?{...d,[key]:value}:d));const updatePago=(i,key,value)=>setPagos(pagos.map((p,n)=>n===i?{...p,[key]:value}:p));
 const emitir=async e=>{e.preventDefault();try{let pendiente=total;const pagosAjustados=pagos.map(p=>{if(p.forma_pago==="Efectivo"&&Number(p.monto)>pendiente){const a={...p,monto:pendiente};pendiente=0;return a}pendiente-=Number(p.monto);return p});await apiFetch("/facturacion",{method:"POST",body:{...form,detalles,pagos:pagosAjustados}});setDetalles([linea()]);setPagos([pago()]);setForm({id_paciente:"",id_receta:"",id_historia:"",id_promocion:"",descuento:0,impuestos:0,dias_credito:30});setMsg("Factura emitida");load()}catch(x){setMsg(x.message)}};
 const ejecutar=async()=>{try{await apiFetch(`/facturacion/${accion.id}/${accion.tipo}`,{method:"POST",body:accionForm});setAccion(null);setMsg(accion.tipo==="anular"?"Factura anulada":"Devolucion registrada");load()}catch(x){setMsg(x.message)}};
 const crearPromo=async e=>{e.preventDefault();try{await apiFetch("/facturacion/promociones",{method:"POST",body:promo});setPromo({nombre:"",porcentaje:""});setMsg("Promocion creada");load()}catch(x){setMsg(x.message)}};
 const imprimir=async id=>{try{setPrintData(await apiFetch(`/facturacion/${id}`));setTimeout(()=>window.print(),200)}catch(x){setMsg(x.message)}};
 return <section className="module-page">{msg&&<div className="notice">{msg}</div>}
 <header className="page-header"><div><span className="eyebrow">Ventas y documentos</span><h1>Facturación</h1><p>Construye la venta por contexto, detalle y pagos; revisa el saldo antes de emitir.</p></div></header><form className="billing-form" onSubmit={emitir}><div className="form-grid"><label>Paciente<select value={form.id_paciente} onChange={e=>setForm({...form,id_paciente:e.target.value})}><option value="">Consumidor final</option>{pacientes.map(p=><option key={p.id_paciente} value={p.id_paciente}>{p.nombre} {p.apellido}</option>)}</select></label><label>ID receta<input type="number" value={form.id_receta} onChange={e=>setForm({...form,id_receta:e.target.value})}/></label><label>ID historia<input type="number" value={form.id_historia} onChange={e=>setForm({...form,id_historia:e.target.value})}/></label><label>Promoción<select value={form.id_promocion} onChange={e=>setForm({...form,id_promocion:e.target.value})}><option value="">Sin promoción</option>{promos.filter(p=>p.activo).map(p=><option key={p.id_promocion} value={p.id_promocion}>{p.nombre} · {p.porcentaje}%</option>)}</select></label><label>Descuento autorizado<input type="number" step="0.01" value={form.descuento} onChange={e=>setForm({...form,descuento:e.target.value})}/></label><label>Impuestos<input type="number" step="0.01" value={form.impuestos} onChange={e=>setForm({...form,impuestos:e.target.value})}/></label><label>Días de crédito<input type="number" value={form.dias_credito} onChange={e=>setForm({...form,dias_credito:e.target.value})}/></label></div>
 <h2>Detalle</h2>{detalles.map((d,i)=><div className="form-grid" key={i}><label>Escanear código<input placeholder="🔍 Código de barras..." onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();const p=productos.find(x=>x.codigo_barra===e.target.value||x.sku===e.target.value);if(p){updateDetalle(i,"id_producto",String(p.id_producto));setDetalles(prev=>prev.map((x,n)=>n===i?{...x,descripcion:p.nombre,precio_unitario:p.precio}:x));e.target.value=""}else{alert("Producto no encontrado")}}}}/></label><label>Producto<select value={d.id_producto} onChange={e=>{const p=productos.find(x=>String(x.id_producto)===e.target.value);updateDetalle(i,"id_producto",e.target.value);setDetalles(prev=>prev.map((x,n)=>n===i?{...x,descripcion:p?.nombre||x.descripcion,precio_unitario:p?.precio||x.precio_unitario}:x))}}><option value="">Servicio</option>{productos.map(p=><option key={p.id_producto} value={p.id_producto}>{p.nombre} ({p.stock})</option>)}</select></label><label>Descripcion<input required value={d.descripcion} onChange={e=>updateDetalle(i,"descripcion",e.target.value)}/></label><label>Cantidad<input required type="number" min="1" value={d.cantidad} onChange={e=>updateDetalle(i,"cantidad",e.target.value)}/></label><label>Precio<input required type="number" step="0.01" value={d.precio_unitario} onChange={e=>updateDetalle(i,"precio_unitario",e.target.value)}/></label><div className="form-actions">{detalles.length>1&&<button type="button" className="secondary" onClick={()=>setDetalles(detalles.filter((_,n)=>n!==i))}>Quitar</button>}</div></div>)}<button type="button" className="secondary" onClick={()=>setDetalles([...detalles,linea()])}>Agregar linea</button>
 <h2>Pagos</h2>{pagos.map((p,i)=><div className="form-grid" key={i}><label>Forma<select value={p.forma_pago} onChange={e=>updatePago(i,"forma_pago",e.target.value)}>{["Efectivo","Tarjeta","Transferencia","Credito","Mixto"].map(x=><option key={x}>{x}</option>)}</select></label><label>Monto<input required type="number" min="0" step="0.01" value={p.monto} onChange={e=>updatePago(i,"monto",e.target.value)}/></label><label>Referencia<input value={p.referencia} onChange={e=>updatePago(i,"referencia",e.target.value)}/></label><div className="form-actions">{pagos.length>1&&<button type="button" className="secondary" onClick={()=>setPagos(pagos.filter((_,n)=>n!==i))}>Quitar</button>}</div></div>)}<button type="button" className="secondary" onClick={()=>setPagos([...pagos,pago()])}>Agregar pago</button><div className="summary-grid billing-summary"><article><span>Subtotal</span><strong>${subtotal.toFixed(2)}</strong></article><article><span>Total</span><strong>${total.toFixed(2)}</strong></article><article><span>Pagado</span><strong>${pagado.toFixed(2)}</strong></article>{pagado>total?<article className="amount-alert"><span>Cambio</span><strong>${(pagado-total).toFixed(2)}</strong></article>:<article><span>Saldo</span><strong>${Math.max(0,total-pagado).toFixed(2)}</strong></article>}</div><button type="submit" disabled={total<=0||pagado<total&&!form.id_paciente}>Emitir factura</button></form>
 {user?.rol==="Administrador"&&<><h2>Promociones</h2><form className="form-grid" onSubmit={crearPromo}><label>Nombre<input required value={promo.nombre} onChange={e=>setPromo({...promo,nombre:e.target.value})}/></label><label>Porcentaje<input required type="number" min="0" max="100" value={promo.porcentaje} onChange={e=>setPromo({...promo,porcentaje:e.target.value})}/></label><div className="form-actions"><button>Crear promocion</button></div></form><p>{promos.filter(p=>p.activo).map(p=>`${p.nombre} (${p.porcentaje}%)`).join(" · ")}</p></>}
 {accion&&<div className="form-grid"><label>Motivo<textarea required value={accionForm.motivo} onChange={e=>setAccionForm({...accionForm,motivo:e.target.value})}/></label>{accion.tipo==="devoluciones"&&<><label>Monto<input type="number" step="0.01" value={accionForm.monto} onChange={e=>setAccionForm({...accionForm,monto:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={accionForm.reponer_stock} onChange={e=>setAccionForm({...accionForm,reponer_stock:e.target.checked})}/>Reponer productos al inventario</label></>}<div className="form-actions"><button onClick={ejecutar}>Confirmar</button><button className="secondary" onClick={()=>setAccion(null)}>Cancelar</button></div></div>}
 <h2>Facturas</h2><div className="table-wrap"><table><thead><tr><th>Numero</th><th>Paciente</th><th>Total</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{facturas.map(f=><tr key={f.id_factura}><td>{f.numero_factura}</td><td>{f.paciente_nombre} {f.paciente_apellido}</td><td>{f.total}</td><td>{f.estado}</td><td>{new Date(f.creado_en).toLocaleString()}</td><td><button onClick={()=>imprimir(f.id_factura)}>Imprimir</button>{user?.rol==="Administrador"&&f.estado==="Emitida"&&<><button className="secondary" onClick={()=>setAccion({id:f.id_factura,tipo:"anular"})}>Anular</button><button className="secondary" onClick={()=>setAccion({id:f.id_factura,tipo:"devoluciones"})}>Devolver</button></>}</td></tr>)}</tbody></table></div>{printData&&<article className="print-document"><header><div><h1>Óptica Integral</h1><p>Factura</p></div><strong>{printData.numero_factura}</strong></header><p><b>Paciente:</b> {printData.paciente_nombre} {printData.paciente_apellido} · {printData.cedula}</p><p><b>Fecha:</b> {new Date(printData.creado_en).toLocaleString()}</p><table><thead><tr><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Total</th></tr></thead><tbody>{printData.detalles?.map(d=><tr key={d.id_detalle}><td>{d.descripcion}</td><td>{d.cantidad}</td><td>{d.precio_unitario}</td><td>{d.total}</td></tr>)}</tbody></table><div className="summary-grid"><article><span>Subtotal</span><strong>{printData.subtotal}</strong></article><article><span>Descuento</span><strong>{printData.descuento}</strong></article><article><span>Impuestos</span><strong>{printData.impuestos}</strong></article><article><span>Total</span><strong>{printData.total}</strong></article></div></article>}</section>
}
