const pool=require("../../config/database");const audit=require("../../utils/audit");
exports.listar=async()=>(await pool.query(`SELECT f.*,p.nombre AS paciente_nombre,p.apellido AS paciente_apellido FROM facturas f LEFT JOIN pacientes p USING(id_paciente) ORDER BY f.creado_en DESC`)).rows;
exports.obtener=async(id)=>{const r=await pool.query("SELECT * FROM facturas WHERE id_factura=$1",[id]);if(!r.rows[0])throw new Error("Factura no encontrada");r.rows[0].detalles=(await pool.query("SELECT * FROM factura_detalle WHERE id_factura=$1",[id])).rows;r.rows[0].pagos=(await pool.query("SELECT * FROM factura_pagos WHERE id_factura=$1",[id])).rows;return r.rows[0]};
exports.crear=async(data,u,req)=>{const c=await pool.connect();try{await c.query("BEGIN");const detalles=data.detalles||[],pagos=data.pagos||[];if(!detalles.length)throw new Error("La factura requiere detalles");
 const subtotal=detalles.reduce((s,d)=>s+Number(d.cantidad)*Number(d.precio_unitario),0),descuento=Number(data.descuento||0);if(descuento>0&&u.rol!=="Administrador")throw new Error("El descuento requiere permiso de Administrador");if(descuento>subtotal)throw new Error("Descuento invalido");const total=subtotal-descuento,pagado=pagos.reduce((s,p)=>s+Number(p.monto),0);if(pagado>total)throw new Error("Los pagos superan el total");
 const credito=pagos.some(p=>p.forma_pago==="Credito")||pagado<total;if(credito&&data.id_paciente){const venc=await c.query("SELECT 1 FROM cuentas_por_cobrar WHERE id_paciente=$1 AND saldo>0 AND fecha_vencimiento<CURRENT_DATE",[data.id_paciente]);if(venc.rowCount)throw new Error("Cliente bloqueado por saldos vencidos")}
 const caja=await c.query("SELECT id_caja_turno FROM caja_turnos WHERE id_cajero=$1 AND estado='Abierta' ORDER BY abierto_en DESC LIMIT 1",[u.id]);if(!caja.rows[0])throw new Error("Debe abrir caja antes de facturar");
 const numero=data.numero_factura||`FAC-${Date.now()}`;const f=await c.query(`INSERT INTO facturas(id_paciente,id_receta,id_historia,id_caja_turno,numero_factura,subtotal,descuento,total)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[data.id_paciente||null,data.id_receta||null,data.id_historia||null,caja.rows[0].id_caja_turno,numero,subtotal,descuento,total]);
 for(const d of detalles){await c.query("INSERT INTO factura_detalle(id_factura,id_producto,descripcion,cantidad,precio_unitario,total) VALUES($1,$2,$3,$4,$5,$6)",[f.rows[0].id_factura,d.id_producto||null,d.descripcion,Number(d.cantidad),Number(d.precio_unitario),Number(d.cantidad)*Number(d.precio_unitario)]);if(d.id_producto){const p=await c.query("UPDATE productos SET stock=stock-$1 WHERE id_producto=$2 AND stock >= $1 RETURNING id_producto",[Number(d.cantidad),d.id_producto]);if(!p.rowCount)throw new Error(`Stock insuficiente para ${d.descripcion}`)}}
 for(const p of pagos)await c.query("INSERT INTO factura_pagos(id_factura,forma_pago,monto,referencia) VALUES($1,$2,$3,$4)",[f.rows[0].id_factura,p.forma_pago,Number(p.monto),p.referencia||null]);
 if(total-pagado>0&&data.id_paciente)await c.query("INSERT INTO cuentas_por_cobrar(id_paciente,id_factura,saldo,fecha_vencimiento) VALUES($1,$2,$3,CURRENT_DATE+$4::integer)",[data.id_paciente,f.rows[0].id_factura,total-pagado,Number(data.dias_credito||30)]);
 await c.query("COMMIT");await audit({idUsuario:u.id,accion:"FACTURA_EMITIDA",tabla:"facturas",registroId:f.rows[0].id_factura,detalle:{total},req});return f.rows[0];
 }catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}};
exports.anular=async(id,data,u,req)=>{const c=await pool.connect();try{await c.query("BEGIN");const f=await c.query("UPDATE facturas SET estado='Anulada' WHERE id_factura=$1 AND estado='Emitida' RETURNING *",[id]);if(!f.rowCount)throw new Error("Factura no disponible para anulacion");const ds=await c.query("SELECT id_producto,cantidad FROM factura_detalle WHERE id_factura=$1",[id]);for(const d of ds.rows)if(d.id_producto)await c.query("UPDATE productos SET stock=stock+$1 WHERE id_producto=$2",[d.cantidad,d.id_producto]);await c.query("UPDATE cuentas_por_cobrar SET saldo=0,estado='Pagada' WHERE id_factura=$1",[id]);await c.query("INSERT INTO notas_credito(id_factura,motivo,monto,id_usuario) VALUES($1,$2,$3,$4)",[id,data.motivo,f.rows[0].total,u.id]);await c.query("COMMIT");await audit({idUsuario:u.id,accion:"FACTURA_ANULADA",tabla:"facturas",registroId:Number(id),req});return f.rows[0]}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}};
exports.devolver=async(id,data,u,req)=>{const monto=Number(data.monto);const f=await pool.query("SELECT * FROM facturas WHERE id_factura=$1",[id]);if(!f.rows[0]||f.rows[0].estado!=="Emitida")throw new Error("Factura no disponible");if(monto<=0||monto>Number(f.rows[0].total))throw new Error("Monto de devolucion invalido");const r=await pool.query("INSERT INTO devoluciones(id_factura,id_usuario,motivo,monto) VALUES($1,$2,$3,$4) RETURNING *",[id,u.id,data.motivo,monto]);await pool.query("INSERT INTO notas_credito(id_factura,motivo,monto,id_usuario) VALUES($1,$2,$3,$4)",[id,data.motivo,monto,u.id]);await audit({idUsuario:u.id,accion:"DEVOLUCION_REGISTRADA",tabla:"devoluciones",registroId:r.rows[0].id_devolucion,req});return r.rows[0]};
exports.promociones=async()=>(await pool.query("SELECT * FROM promociones ORDER BY nombre")).rows;
exports.crearPromocion=async(data)=>(await pool.query("INSERT INTO promociones(nombre,porcentaje,requiere_permiso,activo) VALUES($1,$2,$3,$4) RETURNING *",[data.nombre,Number(data.porcentaje),data.requiere_permiso!==false,data.activo!==false])).rows[0];
exports.actualizarPromocion=async(id,data)=>{const r=await pool.query("UPDATE promociones SET nombre=$1,porcentaje=$2,requiere_permiso=$3,activo=$4 WHERE id_promocion=$5 RETURNING *",[data.nombre,Number(data.porcentaje),data.requiere_permiso!==false,data.activo!==false,id]);if(!r.rows[0])throw Object.assign(new Error("Promocion no encontrada"),{status:404});return r.rows[0]};
exports.eliminarPromocion=async(id)=>{const r=await pool.query("DELETE FROM promociones WHERE id_promocion=$1 RETURNING *",[id]);if(!r.rows[0])throw Object.assign(new Error("Promocion no encontrada"),{status:404});return r.rows[0]};
