const pool=require("../../config/database");const registrarAuditoria=require("../../utils/audit");
exports.proveedores=async()=>(await pool.query("SELECT * FROM proveedores ORDER BY nombre")).rows;
exports.crearProveedor=async(data)=>(await pool.query(`INSERT INTO proveedores(nombre,ruc,telefono,correo,direccion,condiciones_credito,dias_credito)
 VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[data.nombre,data.ruc||null,data.telefono||null,data.correo||null,data.direccion||null,data.condiciones_credito||null,Number(data.dias_credito||0)])).rows[0];
exports.actualizarProveedor=async(id,data)=>{const r=await pool.query(`UPDATE proveedores SET nombre=$1,ruc=$2,telefono=$3,correo=$4,direccion=$5,condiciones_credito=$6,dias_credito=$7 WHERE id_proveedor=$8 RETURNING *`,[data.nombre,data.ruc||null,data.telefono||null,data.correo||null,data.direccion||null,data.condiciones_credito||null,Number(data.dias_credito||0),id]);if(!r.rows[0])throw Object.assign(new Error("Proveedor no encontrado"),{status:404});return r.rows[0]};
exports.eliminarProveedor=async(id)=>{const r=await pool.query("DELETE FROM proveedores WHERE id_proveedor=$1 RETURNING *",[id]);if(!r.rows[0])throw Object.assign(new Error("Proveedor no encontrado"),{status:404});return r.rows[0]};
exports.listar=async()=>(await pool.query(`SELECT o.*,p.nombre AS proveedor,p.ruc,p.telefono,p.correo,p.direccion FROM ordenes_compra o JOIN proveedores p USING(id_proveedor) ORDER BY o.fecha_orden DESC`)).rows;
exports.listarRecepciones=async()=>(await pool.query(`SELECT r.*,o.total,p.nombre proveedor,u.nombre usuario FROM recepciones_compra r JOIN ordenes_compra o USING(id_orden_compra) JOIN proveedores p USING(id_proveedor) LEFT JOIN usuarios u ON u.id_usuario=r.id_usuario ORDER BY r.creado_en DESC`)).rows;
exports.listarDevoluciones=async()=>(await pool.query(`SELECT d.*,p.nombre proveedor FROM devoluciones_proveedor d JOIN proveedores p USING(id_proveedor) ORDER BY d.creado_en DESC`)).rows;
exports.crear=async(data,usuario,req)=>{const client=await pool.connect();try{await client.query("BEGIN");
 const detalles=data.detalles||[];if(!detalles.length)throw new Error("La orden requiere productos");
 const total=detalles.reduce((s,d)=>s+Number(d.cantidad)*Number(d.costo_unitario),0);
 if(!data.id_proveedor||detalles.some(d=>!d.descripcion||Number(d.cantidad)<=0||Number(d.costo_unitario)<0))throw Object.assign(new Error("Proveedor y productos validos son obligatorios"),{status:400});
 const o=await client.query("INSERT INTO ordenes_compra(id_proveedor,id_usuario,total,condiciones_pago,fecha_entrega_estimada) VALUES($1,$2,$3,$4,$5) RETURNING *",[data.id_proveedor,usuario.id,total,data.condiciones_pago||null,data.fecha_entrega_estimada||null]);
 for(const d of detalles)await client.query(`INSERT INTO orden_compra_detalle(id_orden_compra,id_producto,descripcion,cantidad,costo_unitario)
 VALUES($1,$2,$3,$4,$5)`,[o.rows[0].id_orden_compra,d.id_producto||null,d.descripcion,Number(d.cantidad),Number(d.costo_unitario)]);
 await client.query("COMMIT");await registrarAuditoria({idUsuario:usuario.id,accion:"ORDEN_COMPRA_CREADA",tabla:"ordenes_compra",registroId:o.rows[0].id_orden_compra,req});return o.rows[0];
 }catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}};
exports.cancelar=async(id,usuario,req)=>{const r=await pool.query("UPDATE ordenes_compra SET estado='Cancelada' WHERE id_orden_compra=$1 AND estado IN ('Pendiente','Aprobada') RETURNING *",[id]);if(!r.rows[0])throw Object.assign(new Error("Orden no disponible para cancelar"),{status:409});await registrarAuditoria({idUsuario:usuario.id,accion:"ORDEN_COMPRA_CANCELADA",tabla:"ordenes_compra",registroId:Number(id),req});return r.rows[0]};
exports.obtener=async(id)=>{const o=await pool.query(`SELECT o.*,p.nombre proveedor,p.ruc,p.telefono,p.correo,p.direccion FROM ordenes_compra o JOIN proveedores p USING(id_proveedor) WHERE id_orden_compra=$1`,[id]);if(!o.rows[0])throw Object.assign(new Error("Orden no encontrada"),{status:404});
 o.rows[0].detalles=(await pool.query("SELECT * FROM orden_compra_detalle WHERE id_orden_compra=$1 ORDER BY id_detalle",[id])).rows;return o.rows[0]};
exports.recibir=async(id,data,usuario,req)=>{const client=await pool.connect();try{await client.query("BEGIN");
 const orden=await client.query("SELECT * FROM ordenes_compra WHERE id_orden_compra=$1 FOR UPDATE",[id]);if(!orden.rows[0])throw new Error("Orden no encontrada");if(!["Pendiente","Aprobada"].includes(orden.rows[0].estado))throw Object.assign(new Error("La orden no está disponible para recepción"),{status:409});
 const proveedor=await client.query("SELECT dias_credito FROM proveedores WHERE id_proveedor=$1",[orden.rows[0].id_proveedor]);
 const detalles=await client.query("SELECT * FROM orden_compra_detalle WHERE id_orden_compra=$1",[id]);
 const rec=await client.query("INSERT INTO recepciones_compra(id_orden_compra,factura_proveedor,id_usuario,observaciones) VALUES($1,$2,$3,$4) RETURNING *",[id,data.factura_proveedor||null,usuario.id,data.observaciones||null]);
 for(const d of detalles.rows){if(!d.id_producto)continue;await client.query(`UPDATE productos SET costo=CASE WHEN stock+$1>0 THEN ((stock*costo)+($1*$2))/(stock+$1) ELSE $2 END,stock=stock+$1 WHERE id_producto=$3`,[d.cantidad,d.costo_unitario,d.id_producto]);await client.query("INSERT INTO recepcion_compra_detalle(id_recepcion,id_producto,cantidad,costo_unitario) VALUES($1,$2,$3,$4)",[rec.rows[0].id_recepcion,d.id_producto,d.cantidad,d.costo_unitario])}
 await client.query("UPDATE ordenes_compra SET estado='Recibida' WHERE id_orden_compra=$1",[id]);
 if(Number(orden.rows[0].total)>0)await client.query(`INSERT INTO cuentas_por_pagar(id_proveedor,id_orden_compra,saldo,fecha_vencimiento)
 VALUES($1,$2,$3,CURRENT_DATE+$4::integer)`,[orden.rows[0].id_proveedor,id,orden.rows[0].total,Number(data.dias_credito ?? proveedor.rows[0]?.dias_credito ?? 0)]);
 await client.query("COMMIT");await registrarAuditoria({idUsuario:usuario.id,accion:"COMPRA_RECIBIDA",tabla:"recepciones_compra",registroId:rec.rows[0].id_recepcion,req});return rec.rows[0];
 }catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}};
exports.crearDevolucion=async(data,usuario,req)=>{const client=await pool.connect();try{await client.query("BEGIN");const items=data.detalles||[];if(!data.id_recepcion||!data.motivo||!items.length)throw Object.assign(new Error("Recepcion, motivo y productos son obligatorios"),{status:400});const rec=await client.query(`SELECT r.id_recepcion,o.id_proveedor FROM recepciones_compra r JOIN ordenes_compra o USING(id_orden_compra) WHERE r.id_recepcion=$1 FOR UPDATE`,[data.id_recepcion]);if(!rec.rows[0])throw Object.assign(new Error("Recepcion no encontrada"),{status:404});let total=0;for(const item of items){const qty=Number(item.cantidad);const valid=await client.query(`SELECT rd.id_producto,rd.costo_unitario,rd.cantidad-COALESCE((SELECT SUM(dd.cantidad) FROM devolucion_proveedor_detalle dd JOIN devoluciones_proveedor dp USING(id_devolucion_proveedor) WHERE dp.id_recepcion=$1 AND dd.id_producto=rd.id_producto AND dp.estado<>'Cancelada'),0) disponible FROM recepcion_compra_detalle rd WHERE rd.id_recepcion=$1 AND rd.id_producto=$2`,[data.id_recepcion,item.id_producto]);if(!valid.rows[0]||qty<=0||qty>Number(valid.rows[0].disponible))throw Object.assign(new Error("Cantidad de devolucion supera lo recibido"),{status:409});const stock=await client.query("UPDATE productos SET stock=stock-$1 WHERE id_producto=$2 AND stock >= $1 RETURNING id_producto",[qty,item.id_producto]);if(!stock.rows[0])throw Object.assign(new Error("Stock insuficiente para devolver al proveedor"),{status:409});item.costo_unitario=Number(valid.rows[0].costo_unitario);total+=qty*item.costo_unitario}const d=await client.query(`INSERT INTO devoluciones_proveedor(id_proveedor,id_recepcion,id_usuario,numero_nota_credito,motivo,total) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[rec.rows[0].id_proveedor,data.id_recepcion,usuario.id,data.numero_nota_credito||null,data.motivo,total]);for(const item of items)await client.query(`INSERT INTO devolucion_proveedor_detalle(id_devolucion_proveedor,id_producto,cantidad,costo_unitario) VALUES($1,$2,$3,$4)`,[d.rows[0].id_devolucion_proveedor,item.id_producto,Number(item.cantidad),item.costo_unitario]);await client.query("COMMIT");await registrarAuditoria({idUsuario:usuario.id,accion:"DEVOLUCION_PROVEEDOR_CREADA",tabla:"devoluciones_proveedor",registroId:d.rows[0].id_devolucion_proveedor,req});return d.rows[0]}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}};
