import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarPlus, ChevronLeft, ChevronRight, CircleDollarSign, List, Settings2, X } from "lucide-react";
import { apiFetch } from "../../services/api";
import { useAuth } from "../../hooks/useAuth";
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from "../../components/ui";

const empty = { id_paciente:"", fecha_cita:"", hora_cita:"", motivo:"", consultorio:"Consultorio 1", tarifa:"" };
const states = ["Pendiente","Confirmada","Pagada","En atención","Atendida","Cancelada","No asistio"];
const iso = (date) => date.toISOString().slice(0,10);
const startMonth = (date) => new Date(date.getFullYear(),date.getMonth(),1);
const endMonth = (date) => new Date(date.getFullYear(),date.getMonth()+1,0);
const tone = (state) => ({Pendiente:"warning",Confirmada:"info",Pagada:"success","En atención":"info",Atendida:"success",Cancelada:"danger","No asistio":"neutral"}[state] || "neutral");
const keyDate = (value) => String(value || "").slice(0,10);

export default function Citas(){
 const {user}=useAuth();
 const [rows,setRows]=useState([]),[patients,setPatients]=useState([]),[form,setForm]=useState(empty),[creating,setCreating]=useState(false),[manage,setManage]=useState(null),[payment,setPayment]=useState({monto:"",forma_pago:"Efectivo",referencia:""}),[state,setState]=useState("Confirmada"),[message,setMessage]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[view,setView]=useState("month"),[cursor,setCursor]=useState(startMonth(new Date())),[filters,setFilters]=useState({estado:"Todos",paciente:""}),[saving,setSaving]=useState(false);
 const range=useMemo(()=>({desde:iso(startMonth(cursor)),hasta:iso(endMonth(cursor))}),[cursor]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({...range,estado:filters.estado,paciente:filters.paciente});const[c,p]=await Promise.all([apiFetch(`/citas?${params}`),apiFetch("/pacientes?activo=true")]);setRows(c);setPatients(p)}catch(e){setError(e.message)}finally{setLoading(false)}},[range,filters]);
 useEffect(()=>{const timer=setTimeout(load,filters.paciente?250:0);return()=>clearTimeout(timer)},[load,filters.paciente]);
 const save=async(e)=>{e.preventDefault();setSaving(true);try{await apiFetch("/citas",{method:"POST",body:form});setForm(empty);setCreating(false);setMessage("La cita se guardó y ya aparece en la agenda.");await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
 const update=async()=>{setSaving(true);try{await apiFetch(`/citas/${manage.id_cita}`,{method:"PATCH",body:{estado:state}});setManage(null);setMessage("Estado actualizado correctamente.");await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
 const pay=async()=>{setSaving(true);try{await apiFetch(`/citas/${manage.id_cita}/pago-previo`,{method:"POST",body:payment});setManage(null);setPayment({monto:"",forma_pago:"Efectivo",referencia:""});setMessage("Pago previo registrado.");await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
 const canCreate=["Administrador","Cajero","Vendedor"].includes(user?.rol),canPay=["Administrador","Cajero"].includes(user?.rol);
 const days=useMemo(()=>{const first=startMonth(cursor),lead=(first.getDay()+6)%7,total=endMonth(cursor).getDate();return [...Array(lead).fill(null),...Array.from({length:total},(_,i)=>new Date(cursor.getFullYear(),cursor.getMonth(),i+1))]},[cursor]);
 const selectDay=(date)=>{if(!canCreate)return;setForm({...empty,fecha_cita:iso(date)});setCreating(true)};
 return <section className="module-page agenda-page">
  <PageHeader eyebrow="Agenda clínica" title="Citas" description="Consulta el mes visible, filtra y gestiona cada atención sin perder el contexto." actions={canCreate&&<button onClick={()=>setCreating(true)}><CalendarPlus size={17}/>Agendar cita</button>}/>
  {message&&<div className="notice success" role="status">{message}</div>}{error&&<ErrorState message={error} onRetry={load}/>}
  <div className="calendar-toolbar"><div className="calendar-navigation"><button className="secondary icon-button" aria-label="Mes anterior" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft/></button><button className="secondary" onClick={()=>setCursor(startMonth(new Date()))}>Hoy</button><button className="secondary icon-button" aria-label="Mes siguiente" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight/></button><strong>{cursor.toLocaleDateString("es-EC",{month:"long",year:"numeric"})}</strong></div><div className="calendar-filters"><label>Estado<select value={filters.estado} onChange={e=>setFilters({...filters,estado:e.target.value})}><option>Todos</option>{states.map(x=><option key={x}>{x}</option>)}</select></label><label>Paciente<input value={filters.paciente} onChange={e=>setFilters({...filters,paciente:e.target.value})} placeholder="Buscar por nombre"/></label><div className="view-switch" aria-label="Vista de agenda"><button className={view==="month"?"active":"secondary"} onClick={()=>setView("month")}>Mes</button><button className={view==="list"?"active":"secondary"} onClick={()=>setView("list")}><List size={15}/>Lista</button></div></div></div>
  {loading?<LoadingState label="Cargando agenda…"/>:view==="month"?<div className="calendar"><div className="calendar-weekdays">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{days.map((day,index)=><div key={day?iso(day):`blank-${index}`} className={`calendar-day ${!day?"blank":""} ${day&&iso(day)===iso(new Date())?"today":""}`} onDoubleClick={()=>day&&selectDay(day)}>{day&&<><button className="day-number" onClick={()=>selectDay(day)} aria-label={`Agendar el ${day.toLocaleDateString("es-EC")}`}>{day.getDate()}</button><div className="day-events">{rows.filter(r=>keyDate(r.fecha_cita)===iso(day)).map(row=><button key={row.id_cita} className={`appointment ${tone(row.estado)}`} onClick={()=>{setManage(row);setState(row.estado)}}><strong>{String(row.hora_cita).slice(0,5)} · {row.paciente_nombre}</strong><span>{row.estado}</span></button>)}</div></>}</div>)}</div></div>:rows.length?<div className="agenda-list">{rows.map(row=><button key={row.id_cita} onClick={()=>{setManage(row);setState(row.estado)}}><time>{new Date(`${keyDate(row.fecha_cita)}T${String(row.hora_cita).slice(0,5)}`).toLocaleString("es-EC",{dateStyle:"medium",timeStyle:"short"})}</time><span><strong>{row.paciente_apellido} {row.paciente_nombre}</strong><small>{row.motivo||"Sin motivo"} · {row.profesional_nombre}</small></span><StatusBadge tone={tone(row.estado)}>{row.estado}</StatusBadge></button>)}</div>:<EmptyState title="No hay citas en este rango" description="Cambia de mes, ajusta los filtros o agenda una nueva cita."/>}
  {creating&&<div className="drawer-backdrop" onMouseDown={()=>setCreating(false)}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="new-appointment" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">Nueva atención</span><h2 id="new-appointment">Agendar cita</h2></div><button className="icon-button secondary" onClick={()=>setCreating(false)} aria-label="Cerrar"><X/></button></header><form onSubmit={save} className="drawer-form"><label>Paciente *<select required value={form.id_paciente} onChange={e=>setForm({...form,id_paciente:e.target.value})}><option value="">Seleccione</option>{patients.map(p=><option key={p.id_paciente} value={p.id_paciente}>{p.apellido} {p.nombre}</option>)}</select></label><div className="field-grid"><label>Fecha *<input required type="date" value={form.fecha_cita} onChange={e=>setForm({...form,fecha_cita:e.target.value})}/></label><label>Hora *<input required type="time" value={form.hora_cita} onChange={e=>setForm({...form,hora_cita:e.target.value})}/></label><label>Consultorio<input value={form.consultorio} onChange={e=>setForm({...form,consultorio:e.target.value})}/></label><label>Tarifa<input type="number" min="0" step=".01" value={form.tarifa} onChange={e=>setForm({...form,tarifa:e.target.value})}/></label></div><label>Motivo *<textarea required value={form.motivo} onChange={e=>setForm({...form,motivo:e.target.value})}/></label><div className="form-actions"><button disabled={saving}>{saving?"Guardando…":"Guardar cita"}</button><button type="button" className="secondary" onClick={()=>setCreating(false)}>Cancelar</button></div></form></aside></div>}
  {manage&&<div className="drawer-backdrop" onMouseDown={()=>setManage(null)}><aside className="drawer" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">Detalle de cita</span><h2>{manage.paciente_apellido} {manage.paciente_nombre}</h2></div><button className="icon-button secondary" onClick={()=>setManage(null)} aria-label="Cerrar"><X/></button></header><dl className="appointment-detail"><div><dt>Fecha y hora</dt><dd>{keyDate(manage.fecha_cita)} · {String(manage.hora_cita).slice(0,5)}</dd></div><div><dt>Profesional</dt><dd>{manage.profesional_nombre}</dd></div><div><dt>Motivo</dt><dd>{manage.motivo||"Sin detalle"}</dd></div><div><dt>Consultorio</dt><dd>{manage.consultorio||"Sin asignar"}</dd></div><div><dt>Pago registrado</dt><dd>${Number(manage.total_pagado||0).toFixed(2)}</dd></div></dl><label>Estado<select value={state} onChange={e=>setState(e.target.value)}>{states.map(x=><option key={x}>{x}</option>)}</select></label><button disabled={saving} onClick={update}><Settings2 size={16}/>Actualizar estado</button>{canPay&&<section className="payment-box"><h3><CircleDollarSign size={17}/>Registrar pago previo</h3><label>Monto<input type="number" min=".01" step=".01" value={payment.monto} onChange={e=>setPayment({...payment,monto:e.target.value})}/></label><label>Forma<select value={payment.forma_pago} onChange={e=>setPayment({...payment,forma_pago:e.target.value})}>{["Efectivo","Tarjeta","Transferencia","Credito","Mixto"].map(x=><option key={x}>{x}</option>)}</select></label><label>Referencia<input value={payment.referencia} onChange={e=>setPayment({...payment,referencia:e.target.value})}/></label><button disabled={saving||!payment.monto} onClick={pay}>Confirmar pago</button></section>}</aside></div>}
 </section>;
}
