import { useCallback, useEffect, useState } from "react";
import { CalendarPlus, CircleDollarSign, Clock3, Settings2 } from "lucide-react";
import { apiFetch } from "../../services/api";
import { useAuth } from "../../hooks/useAuth";

const empty={id_paciente:"",fecha_cita:"",hora_cita:"",motivo:"",consultorio:"Consultorio 1",tarifa:""};
export default function Citas(){
 const {user}=useAuth();const[rows,setRows]=useState([]),[patients,setPatients]=useState([]),[form,setForm]=useState(empty),[open,setOpen]=useState(false),[manage,setManage]=useState(null),[payment,setPayment]=useState({monto:"",forma_pago:"Efectivo",referencia:""}),[state,setState]=useState("Confirmada"),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{const[c,p]=await Promise.all([apiFetch("/citas"),apiFetch("/pacientes")]);setRows(c);setPatients(p)}catch(error){setMessage(error.message)}},[]);useEffect(()=>{load()},[load]);
 const save=async(event)=>{event.preventDefault();try{await apiFetch("/citas",{method:"POST",body:form});setForm(empty);setOpen(false);setMessage("Cita agendada");load()}catch(error){setMessage(error.message)}};
 const update=async()=>{try{await apiFetch("/citas/"+manage.id_cita,{method:"PATCH",body:{estado:state}});setManage(null);setMessage("Estado actualizado");load()}catch(error){setMessage(error.message)}};
 const pay=async()=>{try{await apiFetch("/citas/"+manage.id_cita+"/pago-previo",{method:"POST",body:payment});setManage(null);setPayment({monto:"",forma_pago:"Efectivo",referencia:""});setMessage("Pago previo confirmado; la cita puede pasar a atención");load()}catch(error){setMessage(error.message)}};
 const canCreate=["Administrador","Cajero","Vendedor"].includes(user?.rol),canPay=["Administrador","Cajero"].includes(user?.rol);
 return <section className="module-page"><header className="page-header"><div><span className="eyebrow">Agenda clínica</span><h1>Citas y pago previo</h1><p>La atención solo se habilita después de confirmar un pago.</p></div>{canCreate&&<button onClick={()=>setOpen(!open)}><CalendarPlus size={17}/> {open?"Cancelar":"Agendar cita"}</button>}</header>
 {message&&<div className="notice">{message}</div>}
 {open&&<form className="form-grid" onSubmit={save}><label>Paciente<select required value={form.id_paciente} onChange={(e)=>setForm({...form,id_paciente:e.target.value})}><option value="">Seleccione</option>{patients.map((p)=><option key={p.id_paciente} value={p.id_paciente}>{p.apellido} {p.nombre}</option>)}</select></label><label>Fecha<input required type="date" value={form.fecha_cita} onChange={(e)=>setForm({...form,fecha_cita:e.target.value})}/></label><label>Hora<input required type="time" value={form.hora_cita} onChange={(e)=>setForm({...form,hora_cita:e.target.value})}/></label><label>Consultorio<input value={form.consultorio} onChange={(e)=>setForm({...form,consultorio:e.target.value})}/></label><label>Tarifa<input type="number" min="0" step="0.01" value={form.tarifa} onChange={(e)=>setForm({...form,tarifa:e.target.value})}/></label><label>Motivo<input required value={form.motivo} onChange={(e)=>setForm({...form,motivo:e.target.value})}/></label><div className="form-actions"><button>Guardar cita</button></div></form>}
 {manage&&<section className="clinical-section"><h2><Settings2 size={19}/>Gestionar cita #{manage.id_cita}</h2><div className="summary-grid"><article><span>Paciente</span><strong style={{fontSize:16}}>{manage.paciente_apellido} {manage.paciente_nombre}</strong></article><article><span>Pago registrado</span><strong style={{fontSize:16}}>{"$"}{Number(manage.total_pagado||0).toFixed(2)}</strong></article></div><div className="form-grid"><label>Estado<select value={state} onChange={(e)=>setState(e.target.value)}>{["Pendiente","Confirmada","Pagada","En atención","Atendida","Cancelada","No asistio"].map((item)=><option key={item}>{item}</option>)}</select></label><div className="form-actions"><button onClick={update}>Actualizar estado</button></div>{canPay&&<><label>Monto<input type="number" min=".01" step=".01" value={payment.monto} onChange={(e)=>setPayment({...payment,monto:e.target.value})}/></label><label>Forma de pago<select value={payment.forma_pago} onChange={(e)=>setPayment({...payment,forma_pago:e.target.value})}>{["Efectivo","Tarjeta","Transferencia","Credito","Mixto"].map((item)=><option key={item}>{item}</option>)}</select></label><label>Referencia<input value={payment.referencia} onChange={(e)=>setPayment({...payment,referencia:e.target.value})}/></label><div className="form-actions"><button onClick={pay}><CircleDollarSign size={16}/> Confirmar pago</button></div></>}</div><button className="secondary" onClick={()=>setManage(null)}>Cerrar</button></section>}
 <div className="table-wrap"><table><thead><tr><th>Fecha y hora</th><th>Paciente</th><th>Motivo</th><th>Consultorio</th><th>Pago</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id_cita}><td><Clock3 size={13}/> {String(row.fecha_cita).slice(0,10)} · {String(row.hora_cita).slice(0,5)}</td><td>{row.paciente_apellido} {row.paciente_nombre}</td><td>{row.motivo}</td><td>{row.consultorio||"—"}</td><td><span className="status-pill"><span/>{"$"}{Number(row.total_pagado||0).toFixed(2)}</span></td><td>{row.estado}</td><td><button onClick={()=>{setManage(row);setState(row.estado)}}>Gestionar</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No hay citas registradas.</div>}</div>
 </section>;
}
