import {useCallback,useEffect,useState} from "react";
import {apiFetch} from "../../services/api";
const proveedorInicial={nombre:"",ruc:"",telefono:"",correo:"",direccion:"",condiciones_credito:"",dias_credito:0};
const linea={id_producto:"",descripcion:"",cantidad:1,costo_unitario:""};
const money=n=>Number(n||0).toLocaleString("es-EC",{style:"currency",currency:"USD"});
export default function Compras(){
 const[ordenes,setOrdenes]=useState([]),[proveedores,setProveedores]=useState([]),[productos,setProductos]=useState([]),[recepciones,setRecepciones]=useState([]),[proveedor,setProveedor]=useState(proveedorInicial),[orden,setOrden]=useState({id_proveedor:"",condiciones_pago:"",fecha_entrega_estimada:"",detalles:[{...linea}]}),[recepcion,setRecepcion]=useState(null),[datosRec,setDatosRec]=useState({factura_proveedor:"",dias_credito:0,observaciones:""}),[printData,setPrintData]=useState(null),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{try{const[o,p,pr,r]=await Promise.all([apiFetch("/compras"),apiFetch("/compras/proveedores"),apiFetch("/inventario"),apiFetch("/compras/recepciones")]);setOrdenes(o);setProveedores(p);setProductos(pr);setRecepciones(r)}catch(e){setMsg(e.message)}},[]);useEffect(()=>{load()},[load]);
 const crearProveedor=async e=>{e.preventDefault();try{await apiFetch("/compras/proveedores",{method:"POST",body:proveedor});setProveedor(proveedorInicial);setMsg("Proveedor creado");load()}catch(x){setMsg(x.message)}};
 const setDetalle=(i,data)=>setOrden({...orden,detalles:orden.detalles.map((d,n)=>n===i?{...d,...data}:d)});
 const seleccionar=(i,id)=>{const p=productos.find(x=>String(x.id_producto)===id);setDetalle(i,{id_producto:id,descripcion:p?.nombre||"",costo_unitario:p?.costo||""})};
 const crearOrden=async e=>{e.preventDefault();try{await apiFetch("/compras",{method:"POST",body:orden});setOrden({id_proveedor:"",condiciones_pago:"",fecha_entrega_estimada:"",detalles:[{...linea}]});setMsg("Orden creada");load()}catch(x){setMsg(x.message)}};
 const recibir=async()=>{try{await apiFetch(`/compras/${recepcion}/recibir`,{method:"POST",body:datosRec});setRecepcion(null);setMsg("Recepción registrada e inventario actualizado");load()}catch(x){setMsg(x.message)}};
 const imprimirOrden=async id=>{try{setPrintData({...await apiFetch(`/compras/${id}`),tipo:"orden"});setTimeout(()=>window.print(),50)}catch(x){setMsg(x.message)}};
 const total=orden.detalles.reduce((s,d)=>s+Number(d.cantidad||0)*Number(d.costo_unitario||0),0);
 return <section className="module-page"><header className="page-header"><div><h1>Compras</h1><p>Orden → recepción → inventario</p></div></header>{msg&&<div className="notice">{msg}</div>}
 <details><summary><strong>Registrar proveedor</strong></summary><form className="form-grid" onSubmit={crearProveedor}>{Object.keys(proveedorInicial).map(k=><label key={k}>{k.replaceAll("_"," ")}<input type={k==="dias_credito"?"number":"text"} required={k==="nombre"} value={proveedor[k]} onChange={e=>setProveedor({...proveedor,[k]:e.target.value})}/></label>)}<div className="form-actions"><button>Guardar proveedor</button></div></form></details>
 <h2>Nueva orden de compra</h2><form className="clinical-section" onSubmit={crearOrden}><div className="field-grid cols-3"><label>Proveedor<select required value={orden.id_proveedor} onChange={e=>setOrden({...orden,id_proveedor:e.target.value})}><option value="">Seleccione</option>{proveedores.map(p=><option key={p.id_proveedor} value={p.id_proveedor}>{p.nombre}</option>)}</select></label><label>Condiciones de pago<input required value={orden.condiciones_pago} onChange={e=>setOrden({...orden,condiciones_pago:e.target.value})} placeholder="Contado / crédito 30 días"/></label><label>Entrega estimada<input type="date" value={orden.fecha_entrega_estimada} onChange={e=>setOrden({...orden,fecha_entrega_estimada:e.target.value})}/></label></div>{orden.detalles.map((d,i)=><div className="purchase-line" key={i}><label>Producto<select required value={d.id_producto} onChange={e=>seleccionar(i,e.target.value)}><option value="">Seleccione</option>{productos.map(p=><option key={p.id_producto} value={p.id_producto}>{p.nombre}</option>)}</select></label><label>Descripción<input required value={d.descripcion} onChange={e=>setDetalle(i,{descripcion:e.target.value})}/></label><label>Cantidad<input required type="number" min="1" value={d.cantidad} onChange={e=>setDetalle(i,{cantidad:e.target.value})}/></label><label>Costo unitario<input required type="number" min="0" step="0.01" value={d.costo_unitario} onChange={e=>setDetalle(i,{costo_unitario:e.target.value})}/></label>{orden.detalles.length>1&&<button type="button" className="secondary" onClick={()=>setOrden({...orden,detalles:orden.detalles.filter((_,n)=>n!==i)})}>Quitar</button>}</div>)}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setOrden({...orden,detalles:[...orden.detalles,{...linea}]})}>Agregar producto</button><strong>Total: {money(total)}</strong><button>Crear orden</button></div></form>
 {recepcion&&<div className="clinical-section"><h2>Recepción de orden #{recepcion}</h2><div className="form-grid"><label>Factura del proveedor<input required value={datosRec.factura_proveedor} onChange={e=>setDatosRec({...datosRec,factura_proveedor:e.target.value})}/></label><label>Días de crédito<input type="number" min="0" value={datosRec.dias_credito} onChange={e=>setDatosRec({...datosRec,dias_credito:e.target.value})}/></label><label>Observaciones<textarea value={datosRec.observaciones} onChange={e=>setDatosRec({...datosRec,observaciones:e.target.value})}/></label><div className="form-actions"><button onClick={recibir}>Confirmar recepción</button><button className="secondary" onClick={()=>setRecepcion(null)}>Cancelar</button></div></div></div>}
 <h2>Órdenes</h2><div className="table-wrap"><table><thead><tr><th>Orden</th><th>Proveedor</th><th>Fecha</th><th>Pago</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{ordenes.map(o=><tr key={o.id_orden_compra}><td>OC-{String(o.id_orden_compra).padStart(6,"0")}</td><td>{o.proveedor}</td><td>{new Date(o.fecha_orden).toLocaleDateString()}</td><td>{o.condiciones_pago||"—"}</td><td>{money(o.total)}</td><td>{o.estado}</td><td><button onClick={()=>imprimirOrden(o.id_orden_compra)}>Imprimir / PDF</button>{["Pendiente","Aprobada"].includes(o.estado)&&<button onClick={()=>setRecepcion(o.id_orden_compra)}>Recibir</button>}</td></tr>)}</tbody></table></div>
 <h2>Recepciones</h2><div className="table-wrap"><table><thead><tr><th>Ingreso</th><th>Orden</th><th>Proveedor</th><th>Factura</th><th>Fecha</th><th>Observaciones</th></tr></thead><tbody>{recepciones.map(r=><tr key={r.id_recepcion}><td>ING-{String(r.id_recepcion).padStart(6,"0")}</td><td>OC-{String(r.id_orden_compra).padStart(6,"0")}</td><td>{r.proveedor}</td><td>{r.factura_proveedor||"—"}</td><td>{new Date(r.creado_en).toLocaleString()}</td><td>{r.observaciones||"—"}</td></tr>)}</tbody></table></div>
 {printData&&<article className="print-document"><header><div><h1>Óptica Integral</h1><p>Orden de compra</p></div><strong>OC-{String(printData.id_orden_compra).padStart(6,"0")}</strong></header><p><b>Proveedor:</b> {printData.proveedor} · <b>RUC:</b> {printData.ruc||"—"}</p><p><b>Contacto:</b> {printData.telefono||"—"} · {printData.correo||"—"}</p><p><b>Dirección:</b> {printData.direccion||"—"}</p><p><b>Emisión:</b> {new Date(printData.fecha_orden).toLocaleString()} · <b>Pago:</b> {printData.condiciones_pago||"—"}</p><table><thead><tr><th>Descripción</th><th>Cantidad</th><th>Precio unitario</th><th>Total</th></tr></thead><tbody>{printData.detalles?.map(d=><tr key={d.id_detalle}><td>{d.descripcion}</td><td>{d.cantidad}</td><td>{money(d.costo_unitario)}</td><td>{money(Number(d.cantidad)*Number(d.costo_unitario))}</td></tr>)}</tbody></table><h2>Total: {money(printData.total)}</h2></article>}</section>
}
