import {useCallback,useEffect,useState} from "react";
import {apiFetch} from "../../services/api";

const proveedorInicial={nombre:"",ruc:"",telefono:"",correo:"",direccion:"",condiciones_credito:"",dias_credito:0};
const ordenInicial={id_proveedor:"",id_producto:"",descripcion:"",cantidad:1,costo_unitario:""};

export default function Compras(){
 const[ordenes,setOrdenes]=useState([]),[proveedores,setProveedores]=useState([]),[productos,setProductos]=useState([]);
 const[proveedor,setProveedor]=useState(proveedorInicial),[orden,setOrden]=useState(ordenInicial),[recepcion,setRecepcion]=useState(null);
 const[datosRec,setDatosRec]=useState({factura_proveedor:"",dias_credito:0}),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{try{const[o,p,pr]=await Promise.all([apiFetch("/compras"),apiFetch("/compras/proveedores"),apiFetch("/inventario")]);setOrdenes(o);setProveedores(p);setProductos(pr)}catch(e){setMsg(e.message)}},[]);
 useEffect(()=>{load()},[load]);
 const crearProveedor=async e=>{e.preventDefault();try{await apiFetch("/compras/proveedores",{method:"POST",body:proveedor});setProveedor(proveedorInicial);setMsg("Proveedor creado");load()}catch(x){setMsg(x.message)}};
 const crearOrden=async e=>{e.preventDefault();try{await apiFetch("/compras",{method:"POST",body:{id_proveedor:orden.id_proveedor,detalles:[{id_producto:orden.id_producto,descripcion:orden.descripcion,cantidad:orden.cantidad,costo_unitario:orden.costo_unitario}]}});setOrden(ordenInicial);setMsg("Orden creada");load()}catch(x){setMsg(x.message)}};
 const recibir=async()=>{try{await apiFetch(`/compras/${recepcion}/recibir`,{method:"POST",body:datosRec});setRecepcion(null);setMsg("Compra recibida e inventario actualizado");load()}catch(x){setMsg(x.message)}};
 return <section className="module-page"><header className="page-header"><div><h1>Compras</h1><p>Proveedores, ordenes y recepciones</p></div></header>{msg&&<div className="notice">{msg}</div>}
 <h2>Nuevo proveedor</h2><form className="form-grid" onSubmit={crearProveedor}>{Object.keys(proveedorInicial).map(k=><label key={k}>{k.replaceAll("_"," ")}<input type={k==="dias_credito"?"number":"text"} required={k==="nombre"} value={proveedor[k]} onChange={e=>setProveedor({...proveedor,[k]:e.target.value})}/></label>)}<div className="form-actions"><button>Guardar proveedor</button></div></form>
 <h2>Nueva orden</h2><form className="form-grid" onSubmit={crearOrden}><label>Proveedor<select required value={orden.id_proveedor} onChange={e=>setOrden({...orden,id_proveedor:e.target.value})}><option value="">Seleccione</option>{proveedores.map(p=><option key={p.id_proveedor} value={p.id_proveedor}>{p.nombre}</option>)}</select></label><label>Producto<select required value={orden.id_producto} onChange={e=>{const p=productos.find(x=>String(x.id_producto)===e.target.value);setOrden({...orden,id_producto:e.target.value,descripcion:p?.nombre||"",costo_unitario:p?.costo||""})}}><option value="">Seleccione</option>{productos.map(p=><option key={p.id_producto} value={p.id_producto}>{p.nombre}</option>)}</select></label><label>Descripcion<input required value={orden.descripcion} onChange={e=>setOrden({...orden,descripcion:e.target.value})}/></label><label>Cantidad<input required type="number" min="1" value={orden.cantidad} onChange={e=>setOrden({...orden,cantidad:e.target.value})}/></label><label>Costo<input required type="number" step="0.01" value={orden.costo_unitario} onChange={e=>setOrden({...orden,costo_unitario:e.target.value})}/></label><div className="form-actions"><button>Crear orden</button></div></form>
 {recepcion&&<div className="form-grid"><label>Factura proveedor<input value={datosRec.factura_proveedor} onChange={e=>setDatosRec({...datosRec,factura_proveedor:e.target.value})}/></label><label>Dias de credito<input type="number" value={datosRec.dias_credito} onChange={e=>setDatosRec({...datosRec,dias_credito:e.target.value})}/></label><div className="form-actions"><button onClick={recibir}>Confirmar recepcion</button><button className="secondary" onClick={()=>setRecepcion(null)}>Cancelar</button></div></div>}
 <div className="table-wrap"><table><thead><tr><th>Orden</th><th>Proveedor</th><th>Fecha</th><th>Total</th><th>Estado</th><th>Accion</th></tr></thead><tbody>{ordenes.map(o=><tr key={o.id_orden_compra}><td>{o.id_orden_compra}</td><td>{o.proveedor}</td><td>{new Date(o.fecha_orden).toLocaleDateString()}</td><td>{o.total}</td><td>{o.estado}</td><td>{o.estado!=="Recibida"&&<button onClick={()=>setRecepcion(o.id_orden_compra)}>Recibir</button>}</td></tr>)}</tbody></table></div></section>
}
